In [1]:
import torch

In [5]:
a = torch.rand(5, 3); a

tensor([[0.1162, 0.4364, 0.6154],
        [0.0361, 0.3043, 0.2003],
        [0.2186, 0.7919, 0.2028],
        [0.2535, 0.3592, 0.3159],
        [0.1574, 0.0857, 0.6120]])

In [6]:
b = torch.rand(5, 3); b

tensor([[0.3196, 0.7783, 0.9221],
        [0.1676, 0.2020, 0.2486],
        [0.7980, 0.9149, 0.4318],
        [0.6365, 0.7883, 0.7364],
        [0.8928, 0.5819, 0.1187]])

In [7]:
# Adding two tensors
a + b

tensor([[0.4358, 1.2146, 1.5375],
        [0.2036, 0.5063, 0.4489],
        [1.0166, 1.7068, 0.6346],
        [0.8900, 1.1475, 1.0524],
        [1.0502, 0.6675, 0.7306]])

In [12]:
#Multiplying two tensors
a*b

tensor([[0.0371, 0.3396, 0.5675],
        [0.0060, 0.0615, 0.0498],
        [0.1744, 0.7245, 0.0876],
        [0.1613, 0.2831, 0.2327],
        [0.1406, 0.0498, 0.0726]])

In [13]:
# Multiply a tensor and a scalar
a*2

tensor([[0.2324, 0.8727, 1.2308],
        [0.0721, 0.6086, 0.4006],
        [0.4371, 1.5837, 0.4057],
        [0.5069, 0.7183, 0.6319],
        [0.3149, 0.1713, 1.2239]])

In [16]:
# Matrix multiplication
m = a@b.T; m

tensor([[0.9442, 0.2606, 0.7577, 0.8712, 0.4307],
        [0.4331, 0.1173, 0.3937, 0.4103, 0.2330],
        [0.8732, 0.2470, 0.9865, 0.9127, 0.6800],
        [0.6519, 0.1936, 0.6673, 0.6771, 0.4728],
        [0.6813, 0.1958, 0.4683, 0.6184, 0.2630]])

In [25]:
n = 1000

In [26]:
x = torch.rand(n, n)
y = torch.rand(n, n)

In [27]:
%timeit x@y

11.8 ms ± 150 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [28]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = x.to(device)
    y = y.to(device)
    %timeit x@y
    

513 µs ± 2.63 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
